name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 16.x
        uses: actions/setup-node@main
        with:
          node-version: 16
          check-latest: true

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
  CodeQL:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v2
      
      - name: "CodeQL: Initialize"
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
          
      - name: "CodeQL: Autobuild"
        uses: github/codeql-action/autobuild@v1
        
      - name: "CodeQL: Analysis"
        uses: github/codeql-action/analyze@v1
